#36 Add api packages control between fileSpecs
corunet/scs-multiapi-plugin pull request #63
Opened 2022-06-16 09:07 UTC by jmejutovazquez

Closes #36

2022-06-16 09:16 UTC, Rivarsal approved these changes

2022-06-16 23:09 UTC, jemacineiras requested changes

2022-06-16 23:09 UTC, jemacineiras commented on README.md
> +  <version>1.5.4</version>
Wrong Version Number

2022-06-17 10:37 UTC, fcampostato approved these changes

2022-06-20 09:40 UTC, jemacineiras approved these changes

2022-06-20 09:46 UTC, merged