#55 Fixed imports processing
corunet/scs-multiapi-plugin pull request #64
Opened 2022-06-16 10:40 UTC by Rivarsal

2022-06-16 11:28 UTC, jemacineiras approved these changes

2022-06-16 15:06 UTC, jmejutovazquez approved these changes

2022-06-16 23:12 UTC, jemacineiras requested changes

2022-06-16 23:12 UTC, jemacineiras commented on src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperPathUtil.java
> +                                          .contentObject(
This change is not needed.

2022-06-20 09:44 UTC, jemacineiras requested changes

2022-06-20 09:44 UTC, jemacineiras commented on src/main/resources/templates/openapi/templateCallRestClient.ftlh
> +      <#list request.contentObject as content>
Wrong object names. Please keep the previous one.

2022-06-20 10:48 UTC, jemacineiras approved these changes

2022-06-20 14:29 UTC, fcampostato approved these changes

2022-06-20 14:29 UTC, merged