#68 Fix templateSchema
corunet/scs-multiapi-plugin pull request #69
Opened 2022-06-16 16:33 UTC by jmejutovazquez

Closes #68

2022-06-16 23:08 UTC, jemacineiras requested changes

2022-06-16 23:08 UTC, jemacineiras commented on src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiErrorDTO.java
> +
Not needed this empty line

2022-06-16 23:08 UTC, jemacineiras commented on src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestDTO.java
> +
This empty line is not need

2022-06-16 23:08 UTC, jemacineiras commented on src/test/resources/net/coru/api/generator/multiapi/integration/test/ScsMultiapiGenerationTest/testScsMultiapiGeneration/assets/ApiTestInfoDTO.java
> +
Wrong Empty Line

2022-06-16 23:08 UTC, jemacineiras commented on pom.xml
> +  <version>1.5.5</version>
Wrong version number

2022-06-17 08:03 UTC, jemacineiras approved these changes

2022-06-17 08:03 UTC, fcampostato approved these changes

2022-06-17 08:04 UTC, Rivarsal approved these changes

2022-06-17 08:05 UTC, merged