#95 Support allOf to generate model entities
corunet/scs-multiapi-plugin pull request #96
Opened 2022-07-11 12:22 UTC by jmejutovazquez

Closes #95

2022-07-11 12:33 UTC, jemacineiras requested changes

2022-07-11 12:52 UTC, jmejutovazquez commented on src/main/java/net/coru/api/generator/plugin/openapi/utils/MapperPathUtil.java
> +          mapComponents.put(key, type.equalsIgnoreCase(OBJECT) ? MapperUtil.getPojoName(key, fileSpec) : type);
Fixed, thanks for the tip.

2022-07-12 08:12 UTC, Rivarsal approved these changes

2022-07-12 08:52 UTC, jemacineiras approved these changes

2022-07-12 08:55 UTC, merged